# Generated by Django 2.0.2 on 2018-05-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WallPager',
        ),
    ]
