# Generated by Django 2.2.1 on 2020-05-12 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='last_sign',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
