# Generated by Django 2.2.1 on 2019-12-11 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='last_sign',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
