# Generated by Django 2.0.5 on 2018-07-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='describe',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
