# Generated by Django 2.2.1 on 2019-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='buys',
            field=models.ManyToManyField(blank=True, related_name='buy_users', related_query_name='buy_user', to='wallpaper.Wallpaper'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='collects',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='wallpaper.Wallpaper'),
        ),
    ]
