# Generated by Django 2.2.1 on 2020-08-07 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.Wallpaper'),
        ),
        migrations.AlterField(
            model_name='usercollectpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
