# Generated by Django 2.2.1 on 2019-08-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0002_auto_20190809_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appUrl', models.URLField(default='')),
                ('updateInfo', models.CharField(max_length=120)),
                ('isForce', models.BooleanField(default=False)),
                ('versionCode', models.SmallIntegerField()),
                ('versionName', models.CharField(max_length=12)),
            ],
        ),
    ]
