# Generated by Django 2.2.1 on 2020-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0002_auto_20200807_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cos'), (1, '动漫'), (2, '写真')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cos'), (1, '动漫'), (2, '写真')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cos'), (1, '动漫'), (2, '写真')], default=1, verbose_name='类型'),
        ),
    ]
