# Generated by Django 2.2.1 on 2020-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0002_microuser_last_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '动漫'), (1, 'Cos'), (2, '写真')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='source',
            field=models.CharField(default='', max_length=60, verbose_name='来源'),
        ),
    ]
