# Generated by Django 2.0.5 on 2018-07-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_auto_20180702_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
