# Generated by Django 2.0.2 on 2018-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_wallpager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpager',
            name='category',
            field=models.IntegerField(choices=[(0, '风景风光'), (1, '动漫游戏'), (2, '美丽文字'), (3, '萌娃萌宠'), (4, '文化节日'), (5, '美食天下')], default=0),
        ),
    ]
