# Generated by Django 2.2.1 on 2020-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_auto_20200817_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cos'), (1, '动漫'), (2, '写真')], default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cos'), (1, '动漫'), (2, '写真')], default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cos'), (1, '动漫'), (2, '写真')], default=0, verbose_name='类型'),
        ),
    ]
