# Generated by Django 2.2.1 on 2019-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
