# Generated by Django 2.2.1 on 2020-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_auto_20191223_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='share_num',
            field=models.IntegerField(default=0),
        ),
    ]
