# Generated by Django 2.0.2 on 2018-05-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_auto_20180529_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpager',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
