# Generated by Django 2.2.1 on 2019-11-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_auto_20190812_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='today_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.Banner'),
        ),
    ]
