# Generated by Django 2.0.5 on 2018-07-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_auto_20180702_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cover',
            field=models.CharField(default='', max_length=300),
        ),
    ]
