# Generated by Django 2.2.1 on 2020-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_auto_20200114_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='download_num',
            field=models.IntegerField(default=0),
        ),
    ]
