# Generated by Django 2.2.1 on 2020-07-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallpaper.Wallpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
