# Generated by Django 2.2.1 on 2020-09-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
