# Generated by Django 2.0.2 on 2018-05-31 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallpaper', '0006_auto_20180531_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WallPager',
            new_name='Wallpaper',
        ),
    ]
