# Generated by Django 2.0.5 on 2018-07-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_subject_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
