# Generated by Django 2.2.1 on 2020-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_auto_20200921_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='garbage',
            field=models.IntegerField(default=0, verbose_name='被标记为垃圾的次数'),
        ),
    ]
