# Generated by Django 2.0.2 on 2018-05-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_auto_20180531_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='highlighted',
        ),
    ]
