# Generated by Django 2.0.5 on 2018-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_microuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='splash',
            name='cover_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='splash',
            name='link_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cover',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='big_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='small_url',
            field=models.URLField(default=''),
        ),
    ]
