# Generated by Django 2.0.5 on 2018-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0008_auto_20180708_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='sh',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='sw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
