# Generated by Django 2.0.5 on 2018-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0009_auto_20180713_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='tag',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
