# Generated by Django 2.0.5 on 2018-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0010_wallpaper_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='tag',
        ),
        migrations.AddField(
            model_name='subject',
            name='tag',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
