# Generated by Django 2.0.5 on 2018-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0011_auto_20180713_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_2.8858957686589637.jpg', null=True),
        ),
    ]
