# Generated by Django 2.0.5 on 2018-08-12 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0013_auto_20180810_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_2.8972974649236196.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
