# Generated by Django 2.0.5 on 2018-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0015_auto_20180813_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='cover_2',
            new_name='cover2',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='cover_3',
            new_name='cover3',
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_8.167117672357758.jpg', null=True),
        ),
    ]
