# Generated by Django 2.0.5 on 2018-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0018_auto_20180815_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_9.636229507219674.jpg', null=True),
        ),
    ]
