# Generated by Django 2.0.5 on 2018-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0019_auto_20180816_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='user_supported',
            new_name='supported',
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_2.321942424458822.jpg', null=True),
        ),
    ]
