# Generated by Django 2.0.5 on 2018-08-20 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0020_auto_20180817_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_11.997138328823812.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='support_people',
            field=models.ManyToManyField(blank=True, related_name='subject_support', to=settings.AUTH_USER_MODEL),
        ),
    ]
