# Generated by Django 2.0.5 on 2018-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0024_auto_20180820_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bcy_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_6.46946875826758.jpg'),
        ),
    ]
