# Generated by Django 2.0.5 on 2018-12-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0025_auto_20180905_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='bcy_id',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='wallpaper',
            old_name='big_url',
            new_name='origin_url',
        ),
        migrations.RenameField(
            model_name='wallpaper',
            old_name='small_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='source',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_8.119228368519721.jpg'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='source',
            field=models.CharField(default='', max_length=60),
        ),
    ]
