# Generated by Django 2.0.5 on 2018-12-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0026_auto_20181214_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='support_people',
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_2.1939293163192666.jpg'),
        ),
    ]
