# Generated by Django 2.0.5 on 2018-12-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0027_auto_20181226_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_6.596519430642767.jpg'),
        ),
    ]
