# Generated by Django 2.0.5 on 2019-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0028_auto_20181228_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cover_1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='cover_2',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(blank=True, default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_4.72516766414105.jpg'),
        ),
    ]
