# Generated by Django 2.1.7 on 2019-04-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0032_auto_20190419_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_11.438055164632193.jpg'),
        ),
    ]
