# Generated by Django 2.1.7 on 2019-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0033_auto_20190419_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='isLogin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_7.229054213712581.jpg'),
        ),
    ]
