# Generated by Django 2.1.7 on 2019-05-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0034_auto_20190516_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='owner',
        ),
        migrations.AddField(
            model_name='microuser',
            name='wallpapers',
            field=models.ManyToManyField(to='wallpaper.Wallpaper'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_9.726186994413501.jpg'),
        ),
    ]
