# Generated by Django 2.1.7 on 2019-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0035_auto_20190524_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(default='\thttp://wallpager-1251812446.cosbj.myqcloud.com/avatar/default_avatar_9.9928716662209.jpg'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='wallpapers',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='wallpaper.Wallpaper'),
        ),
    ]
