# Generated by Django 2.1.7 on 2019-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0035_auto_20190524_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('type', models.SmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='microuser',
            name='avatar',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='wallpapers',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='wallpaper.Wallpaper'),
        ),
    ]
