# Generated by Django 2.1.7 on 2019-05-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0037_banner_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
