# Generated by Django 2.1.7 on 2019-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0038_auto_20190530_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microuser',
            name='wallpapers',
        ),
        migrations.AddField(
            model_name='microuser',
            name='collects',
            field=models.ManyToManyField(related_name='collects', to='wallpaper.Wallpaper'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
