# Generated by Django 2.1.7 on 2019-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0040_auto_20190626_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='sex',
            field=models.SmallIntegerField(default=0),
        ),
    ]
