# Generated by Django 2.1.7 on 2019-07-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0041_microuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='collect_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='collects',
            field=models.ManyToManyField(related_name='users', to='wallpaper.Wallpaper'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='wallpaper.Category'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='wallpaper.Subject'),
        ),
    ]
