# Generated by Django 2.1.7 on 2019-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0042_auto_20190709_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='buys',
            field=models.ManyToManyField(related_name='buy_users', to='wallpaper.Wallpaper'),
        ),
        migrations.AddField(
            model_name='microuser',
            name='pea',
            field=models.IntegerField(default=10),
        ),
    ]
