# Generated by Django 2.1.7 on 2019-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0043_auto_20190717_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='buys',
            field=models.ManyToManyField(related_name='buy_users', related_query_name='buy_user', to='wallpaper.Wallpaper'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='collects',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='wallpaper.Wallpaper'),
        ),
    ]
