# Generated by Django 2.1.7 on 2019-08-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0045_wallpaper_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.Banner'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.Category'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallpaper.Subject'),
        ),
    ]
