# Generated by Django 2.1.7 on 2019-08-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0046_auto_20190802_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_papers', to='wallpaper.Banner'),
        ),
    ]
